services:
  db:
    image: postgres:16
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres # Set a default database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - event_manager

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_DB_SCHEMA=${KC_DB_SCHEMA}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - event_manager

  app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - POSTGRES_APPLICATION_NAME=Event Manager
      - POSTGRES_POOL_SIZE=10
      - POSTGRES_POOL_MAX_OVERFLOW=20
      - TEST_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/test_db
      - TEST_SYNC_DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/test_db
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - event_manager

  stripe:
    image: stripe/stripe-cli:latest
    command: "listen --api-key ${STRIPE_API_KEY} --forward-to app:8001/payments/webhook"
    volumes:
      - ~/.config/stripe:/root/.config/stripe
    env_file:
      - .env
    networks:
      - event_manager

volumes:
  postgres_data:
  # keycloak-data:

networks:
  event_manager:
    driver: bridge
